feat(NestEggsManager): update typings for Egg to include relationships
PteroPackages/PteroJS pull request #28
Opened 2023-06-19 07:59 UTC by enxg

This PR adds typing for relationships returned when they are included via the `FetchOptions`.
I wasn't able to add typings for `config` and `script`, since I wasn't able to get a response from the API that included them.

2023-06-21 03:42 UTC, devnote-dev requested changes
Sorry to be pedantic, but these interface structures aren't going to work for this. Relationship fields aren't accessible via a `relationships` field, instead all the fields in the relationships become part of the main object (and are `undefined` when not referenced/included in the request). It's a mistake I made in the early days of PteroJS that would require quite a lot of rewriting to fix, not to mention a big breaking change.

2023-06-21 06:48 UTC, enxg commented
I was able to access them using the `relationships` fields after ts-ignoring everything (obviously typescript wasn't happy), I would love to make something with generics so that types were only included when they were in the `FetchOptions`, but I'm not that experienced with generics.

2023-06-24 00:40 UTC, devnote-dev commented
Sorry, I should rephrase: the issue isn't accessing the fields, the Pterodactyl API intends for you to map the data structures via the `relationships` field, it's just not what happened for PteroJS though. Relationship fields are mapped into the parent object directly (for example, including the node a server belongs to in the application API will define the `node` field). Merging this change would make it inconsistent with the rest of the library; the fields need to be part of the egg interface directly.

2023-06-25 07:17 UTC, enxg commented
> Sorry, I should rephrase: the issue isn't accessing the fields, the Pterodactyl API intends for you to map the data structures via the `relationships` field, it's just not what happened for PteroJS though. Relationship fields are mapped into the parent object directly (for example, including the node a server belongs to in the application API will define the `node` field). Merging this change would make it inconsistent with the rest of the library; the fields need to be part of the egg interface directly.

ah, ok then.

2023-06-25 07:17 UTC, closed without merging